### ISSUE TITLE
It is unclear if plugins are for the admin or for users

### ISSUE THREAD

**Issue by vporton** [jhmaverick/vestacp-plugin-manager#1]
**Describe the bug**
From the README file, it's unclear if the plugins functions that add to menu add new functionality for the administrator or for users. (Personally I need new functionality for users.)

**Comment by jhmaverick** [comment]
Hello,

In the fourth parameter of the function "add_header_menu" it is possible to define where the menu will be displayed(all_users or admin_panel). When the parameter is not entered, "all_users" is used by default.

The function above controls only what is displayed in the menu, for plugins that should be available only in the admin, a validation must be applied to its index to prevent users from accessing the plugin directly by the URL.

```php
if ($user != 'admin') {
    exit;
}
```
